[package]
name = "rust"
version = "0.1.0"
authors = []

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { git = 'https://github.com/alexcrichton/wasm-bindgen' }

[profile.dev]
opt-level = 's'
panic = 'abort'

debug-assertions = false
overflow-checks = false
debug = false

[profile.release]
opt-level = 's'
panic = 'abort'
