[package]
name = "rust"
version = "0.1.0"
authors = []

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.1"

[profile.dev]
panic = 'abort'

# to see the release binary in development (for size reasons mostly) uncomment
# these lines
#opt-level = 's'
#lto = 's'
#debug = false
#overflow-checks = false
#debug-assertions = false

[profile.release]
opt-level = 's'
panic = 'abort'
lto = true
